services:
  event_db:
    image: postgres:16
    container_name: eventhub_event_db

    environment:
      POSTGRES_DB: eventhub_event_db
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123

    ports:
      - "5433:5432"

    volumes:
      - event_db_data:/var/lib/postgresql/data



  user_db:
    image: postgres:16
    container_name: eventhub_user_db
    environment:
      POSTGRES_DB: eventhub_user_db
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123
    ports:
      - "5434:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  keycloak_db:
    image: postgres:16
    container_name: eventhub_keycloak_db

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123

    ports:
      - "5435:5432"

    volumes:
      - keycloak_db_data:/var/lib/postgresql/data


  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    container_name: eventhub_keycloak

    command: start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123

    ports:
      - "8083:8080"

    depends_on:
      - keycloak_db

  media-db:
    image: postgres:16
    container_name: eventhub_media_db
    environment:
      POSTGRES_DB: eventhub_media_db
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123
    ports:
      - "5436:5432"
    volumes:
      - media_db_data:/var/lib/postgresql/data


  booking-db:
    image: postgres:16
    container_name: eventhub_booking_db
    environment:
      POSTGRES_DB: eventhub_booking_db
      POSTGRES_USER: eventhub
      POSTGRES_PASSWORD: eventhub123
    ports:
      - "5437:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    container_name: eventhub_minio
    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: eventhub
      MINIO_ROOT_PASSWORD: eventhub123

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data


  redis:
    image: redis:7-alpine
    container_name: eventhub-redis
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex


  prometheus:
    image: prom/prometheus:latest
    container_name: eventhub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus


  grafana:
    image: grafana/grafana:latest
    container_name: eventhub-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus


  tempo:
    image: grafana/tempo:latest
    container_name: eventhub-tempo

    command:
      - "-config.file=/etc/tempo.yml"

    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo.yml:ro


volumes:
  event_db_data:
  user_db_data:
  keycloak_db_data:
  media_db_data:
  minio_data:
  booking_db_data:
  prometheus_data:
  grafana_data:
  tempo_data: